ignore-patterns:
  - docs/*
  - packages/grid_control/backends/htcondor_wms/*
  - packages/grid_control_cms/DashboardAPI/*
  - packages/grid_control_cms/Lexicon.py
  - packages/grid_control_cms/share/fragmentForCMSSW.py
  - packages/grid_control_gui/xmpp/*
  - packages/python_compat*
  - packages/requests/*
python-targets:
  - 2
  - 3
strictness: medium
pylint:
  disable:
    - cell-var-from-loop
    - redefined-builtin
    - too-many-arguments
    - unused-argument
