language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - pip install codecov
  - pip install 'coverage<4'
script:
  - export WRAPPER='coverage run -a'
  - $WRAPPER ./go.py -s -o '[jobs] continuous = False' docs/examples/ExampleS1_stresstest.conf
  - $WRAPPER ./go.py docs/examples/ExampleS1_stresstest.conf
  - $WRAPPER ./go.py docs/examples/ExampleS1_stresstest.conf
  - $WRAPPER ./packages/gcUpdatePlugins.py # randomized order
  - $WRAPPER ./packages/gcUpdatePlugins.py
  - $WRAPPER ./packages/gcUpdatePlugins.py
  - $WRAPPER ./packages/gcUpdatePlugins.py
  - $WRAPPER ./packages/gcUpdatePlugins.py
after_success:
  - codecov
